// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Fundo.Domain.Models;

public partial class Loan
{
    public int Id { get; set; }

    public int IdClient { get; set; }

    public string Code { get; set; }

    public string LoanType { get; set; }

    public string Status { get; set; }

    public decimal OriginalAmount { get; set; }

    public decimal OutstandingBalance { get; set; }

    public decimal InterestRate { get; set; }

    public short Term { get; set; }

    public decimal PaymentAmount { get; set; }

    public short PaymentDay { get; set; }

    public DateTime? PaymentDueDate { get; set; }

    public DateTime LastPaymentDate { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ModifiedAt { get; set; }

    public string ModifiedBy { get; set; }

    public Guid RowId { get; set; }

    public virtual Client IdClientNavigation { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
}