// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Fundo.Domain.Models;

public partial class Payment
{
    public int Id { get; set; }

    public int IdLoan { get; set; }

    public decimal PaymentAmount { get; set; }

    public string Description { get; set; }

    public decimal PrincipalPayment { get; set; }

    public decimal InterestPayment { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public Guid RowId { get; set; }

    public virtual Loan IdLoanNavigation { get; set; }
}