// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Fundo.Domain.Models;

public partial class User
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public string Username { get; set; }

    public string PasswordHash { get; set; }

    public bool Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ModifiedAt { get; set; }

    public string ModifiedBy { get; set; }

    public Guid RowId { get; set; }
}