### Host
@host_address = https://localhost:61355

### ********************* LOAN ********************* ###

### Create a new loan
POST {{host_address}}/loans
Content-Type: application/json

{
  "clientCode": "CL0001",
  "loanType": "Personal",
  "originalAmount": 1000,
  "interestRate": 10,
  "paymentDay": 1,
  "term": 12
}

###

### Get loan details by code
GET {{host_address}}/loans/LN0007

###

### List all loans (paged)
GET {{host_address}}/loans?page=1&pageSize=5

###

### Make a payment to a loan
POST {{host_address}}/loans/L001/payment
Content-Type: application/json

{
  "amount": 200,
  "description": "Monthly payment"
}


### ********************* CLIENT ********************* ###

### Create a new client
POST {{host_address}}/clients
Content-Type: application/json

{
  "code": "C00101",
  "identification": "123456789",
  "name": "John Doe",
  "email": "john.doe@example.com",
}

###

### Get client details by code
GET {{host_address}}/clients/C001

###


### ********************* AUTH ********************* ###

### Authenticate - Get JWT Token
POST {{host_address}}/Auth/Authenticate
Content-Type: application/x-www-form-urlencoded

username=client1&password=secret