
CREATE TABLE Clients(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1)
	,Code VARCHAR(50) NOT NULL
	,Identification VARCHAR(50) NOT NULL
	,Name VARCHAR(150) NOT NULL	
	,Email VARCHAR(100)	
	,CreatedAt DATETIME NOT NULL DEFAULT(GETDATE())
	,CreatedBy VARCHAR(50) NOT NULL
	,ModifiedAt DATETIME
	,ModifiedBy VARCHAR(50)
	,RowId UNIQUEIDENTIFIER NOT NULL DEFAULT(NEWID()) 
);

CREATE TABLE Loans(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1)
	,IdClient INT NOT NULL FOREIGN KEY REFERENCES dbo.Clients(Id)
	,Code VARCHAR(50) NOT NULL
	,LoanType VARCHAR(100) NOT NULL
	,Status VARCHAR(50) NOT NULL
	,OriginalAmount NUMERIC(18,2) NOT NULL DEFAULT(0)
	,OutstandingBalance NUMERIC(18,2) NOT NULL DEFAULT(0)
	,InterestRate NUMERIC(5,2) NOT NULL DEFAULT(0) 
	,Term SMALLINT NOT NULL
	,PaymentAmount NUMERIC(18,2) NOT NULL DEFAULT(0)
	,PaymentDay SMALLINT NOT NULL
	,PaymentDueDate DATETIME
	,LastPaymentDate DATETIME
	,CreatedAt DATETIME NOT NULL DEFAULT(GETDATE())
	,CreatedBy VARCHAR(50) NOT NULL
	,ModifiedAt DATETIME
	,ModifiedBy VARCHAR(50)
	,RowId UNIQUEIDENTIFIER NOT NULL DEFAULT(NEWID()) 
);

CREATE TABLE Payments(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1)
	,IdLoan INT NOT NULL FOREIGN KEY REFERENCES dbo.Loans(Id)
	,PaymentAmount NUMERIC(18,2) NOT NULL DEFAULT(0)
	,Description VARCHAR(100)
	,PrincipalPayment NUMERIC(18,2) NOT NULL DEFAULT(0)
	,InterestPayment NUMERIC(18,2) NOT NULL DEFAULT(0)
	,CreatedAt DATETIME NOT NULL DEFAULT(GETDATE())
	,CreatedBy VARCHAR(50) NOT NULL
	,RowId UNIQUEIDENTIFIER NOT NULL DEFAULT(NEWID()) 
);

CREATE TABLE Users(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1)
	,Code VARCHAR(50) NOT NULL
	,Name VARCHAR(150) NOT NULL	
	,Username VARCHAR(150) NOT NULL	
	,PasswordHash VARCHAR(MAX) NOT NULL	
	,Status BIT NOT NULL DEFAULT(0)
	,CreatedAt DATETIME NOT NULL DEFAULT(GETDATE())
	,CreatedBy VARCHAR(50) NOT NULL
	,ModifiedAt DATETIME
	,ModifiedBy VARCHAR(50)
	,RowId UNIQUEIDENTIFIER NOT NULL DEFAULT(NEWID()) 
);